import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "../../components/Header";
import { Icon } from "../../components/Icon";
import { confessionalSource, editorialNotice } from "../../content/sanctuary";

export const metadata: Metadata = { title: "Fontes e critérios editoriais" };

export default function AboutPage() {
  return <><Header active="about" /><main id="conteudo" className="article-page"><p className="eyebrow"><span className="little-line" /> SOBRE O SANCTUARY360</p><h1>Explorar com curiosidade.<br /><em>Estudar com responsabilidade.</em></h1><p className="article-lead">Uma experiência educacional independente para aproximar o estudo bíblico da compreensão espacial do Tabernáculo do deserto.</p><div className="editorial-banner">{editorialNotice}</div>
    <section className="about-section"><h2>Três camadas de informação</h2><ul><li><strong>Descrição bíblica:</strong> o que as passagens descrevem, com referências e resumos autorais.</li><li><strong>Reconstrução visual:</strong> decisões necessárias para representar aspectos que o texto não detalha.</li><li><strong>Interpretação teológica:</strong> conexões explícitas no Novo Testamento e aplicações adventistas, identificadas separadamente.</li></ul><p>As bases principais são Êxodo 25–40, Levítico 1–7 e 16, e Hebreus 8–10. Cada elemento do guia traz suas referências específicas. Não misturamos o Tabernáculo do deserto com os templos de Salomão ou Herodes.</p></section>
    <section className="about-section"><h2>Identidade e limites teológicos</h2><p>O projeto adota a perspectiva adventista do sétimo dia, sem apresentar suas formulações confessionais como consenso entre todos os cristãos. O sacrifício único e suficiente de Cristo é distinguido de seu ministério sacerdotal. A síntese do tour apresenta 1844 e o juízo investigativo como interpretação adventista, não como datas ou explicações arquitetônicas expressas em Hebreus.</p><p>A fonte confessional é a <a href={confessionalSource.url}>Crença Fundamental 24 — O ministério de Cristo no santuário celestial</a>. Não há alegação de vínculo oficial, aprovação institucional ou revisão teológica concluída.</p><p>O tour é uma visita didática, não a execução de um ritual único. A entrada no Lugar Santo era sacerdotal; o acesso ao Santíssimo era reservado ao sumo sacerdote no serviço anual, conforme Levítico 16 e Hebreus 9:6–7.</p></section>
    <section className="about-section"><h2>O que o modelo pode — e não pode — mostrar</h2><p>As geometrias são geradas em código. A escala usa côvados; a conversão de 0,4572 m por côvado é aproximada e declarada. Medidas não informadas, como as da bacia e do candelabro, não são cadastradas como dados bíblicos. As dimensões convencionais da tenda e seus compartimentos envolvem interpretação de Êxodo 26.</p><p>Cores, tecidos, espessuras, querubins, suportes e distribuição exata dos pilares são esquemáticos. Coberturas são representadas de forma simplificada, não como reconstituição completa de todas as camadas. O modelo terrestre não é uma reprodução comprovada da arquitetura celestial, e não há representação física de Deus na cena.</p></section>
    <section className="about-section"><h2>Acesso e direitos de uso</h2><p>Todo o conteúdo está disponível no <Link href="/estudo">guia textual</Link>, sem depender de WebGL ou JavaScript. O tour não avança sozinho. Transições respeitam a preferência por movimento reduzido do sistema.</p><p>Os textos são resumos autorais e não reproduções literais de uma tradução bíblica. Nenhuma imagem, modelo comprado ou fonte remota é necessária para esta versão. Antes da publicação pública, são necessárias revisão teológica humana e verificação editorial e de direitos. A licença do código ainda não foi definida.</p></section>
    <Link href="/" className="button primary" style={{ marginTop: 30 }}><Icon name="compass" size={18} />Começar a explorar<Icon name="arrow" size={17} /></Link></main></>;
}
