import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "../../components/Header";
import { Icon } from "../../components/Icon";
import { confessionalSource, editorialNotice, elements } from "../../content/sanctuary";
import { formatDimension } from "../../lib/measurements";

export const metadata: Metadata = { title: "Guia de estudo" };

export default function StudyPage() {
  return <><Header active="study" /><main id="conteudo" className="article-page"><p className="eyebrow"><span className="little-line" /> GUIA DE ESTUDO</p><h1>Primeiro, o texto.<br /><em>Depois, a descoberta.</em></h1><p className="article-lead">Todo o conteúdo do percurso em uma página. Sem depender de 3D, gestos ou JavaScript. Use também a impressão do navegador para estudar em papel.</p><div className="editorial-banner">{editorialNotice}</div><Link href="/" className="button primary"><Icon name="cube" size={18} />Voltar à exploração 3D<Icon name="arrow" size={17} /></Link><nav className="study-index" aria-label="Índice do guia">{elements.map((element) => <a href={`#${element.id}`} key={element.id}>{element.number} · {element.name}</a>)}</nav>
    {elements.map((element) => <article id={element.id} className="study-article" key={element.id}><p className="eyebrow">{element.number} · {element.zone.toUpperCase()}</p><h2>{element.name}</h2><span className="content-label">DESCRIÇÃO BÍBLICA · RESUMO AUTORAL</span><p>{element.description}</p>{element.materials.length > 0 && <><h3>Materiais</h3><p>{element.materials.join(" · ")}</p></>}{element.dimensions.length > 0 && <><h3>Medidas documentadas</h3><dl className="dimensions">{element.dimensions.map((dimension) => <div key={dimension.label}><dt>{dimension.label}</dt><dd>{formatDimension(dimension.cubits, "cubits")}</dd></div>)}</dl></>}<h3>Referências e contexto</h3>{element.references.map((reference) => <section className="reference-card" key={reference.passage}><strong>{reference.passage}</strong><p>{reference.summary}</p></section>)}<h3>Interpretação teológica</h3><span className="content-label">PERSPECTIVA ADVENTISTA DO SÉTIMO DIA</span><p>{element.theology}</p><ul>{element.theologyRefs.map((reference) => <li key={reference}>{reference}</li>)}</ul><h3>Sobre a reconstrução</h3><span className="content-label">{element.certainty.toUpperCase()}</span><p>{element.reconstruction}</p></article>)}
    <section className="about-section"><h2>Convenções e fonte confessional</h2><p>1 unidade 3D corresponde a 1 côvado. Adotamos 0,4572 m por côvado apenas como convenção de conversão; o comprimento histórico varia. O pátio segue 100 × 50 côvados e cortinas de 5 côvados (Êxodo 27:9–18). A tenda de 30 × 10 × 10 é uma reconstrução convencional a partir de Êxodo 26, não uma planta completa fornecida pelo texto.</p><p>Espessuras, distribuição dos pilares, suportes, pisos destacados, coberturas e posições exatas são simplificados. Nem todos os detalhes construtivos estão representados. Ocultar paredes e véu é uma ferramenta de estudo, não uma reconstituição do acesso antigo.</p><p><a href={confessionalSource.url}>{confessionalSource.label}</a></p><p>Projeto independente, sem alegação de vínculo oficial ou aprovação institucional. A licença do projeto e a tradução bíblica para eventuais citações literais ainda não foram definidas.</p></section></main></>;
}
